#ifndef CANVAS_H
#define CANVAS_H

#include <Arduino.h>
#include "Elements.h"
#include "APIData.h"

class Canvas {

  std::vector<Elements::Text *> elements;

  std::vector<Elements::Generic *> APIElements;
  APIData apiobj;

public:

  Canvas() {}

  // refresh elements generated by API data
  void update();

  void addElement(Elements::Text * e);

  void resetElements();

  std::vector<Elements::Text *> getElements();

  String getElementsString();

  void draw(LEDController * controller);

  void setElements(char * content);

  void setAPI(String name, String url, long refresh, bool active, std::map<String, APIParseRule> parseRules);

  void resetAPI();

  void toggleAPI();

  APIData getAPIData();

  void updateAPI(unsigned long curtime);
};

#endif
